- name: Create foto e video directory
  file:
    path: /home/pi/foto_e_video
    state: directory

- name: Create telecamere directory
  file:
    path: /home/pi/telecamere
    state: directory

- name: Install ntfs-3g
  become: true
  apt:
    name: ntfs-3g
    state: present

- name: Install and configure Samba
  become: true
  apt:
    name: samba
    state: present

- name: Download and Install cockpit-samba-manager
  become: true
  shell: wget https://github.com/45Drives/cockpit-samba-manager/releases/download/v1.0.6/cockpit-samba-manager_1.0.6-1focal_all.deb

- name: Download and Install cockpit-samba-manager
  become: true
  shell: apt install -y ./cockpit-samba-manager_1.0.6-1focal_all.deb

- name: Include registry section in smb.conf
  become: true
  lineinfile:
    path: /etc/samba/smb.conf
    line: 'include = registry'
    state: present
    insertafter: '\[global\]'

- name: Restart Samba service
  become: true
  service:
    name: smbd
    state: restarted

- name: Restart Cockpit service
  become: true
  service:
    name: cockpit.socket
    state: restarted

