---
- name: Create directories and copy docker-compose files
  hosts: localhost
  become: true
  tasks:
  - name: Create pihole directory
    file:
      path: /home/pi/pihole
      state: directory
    tags: pihole
  - name: Copy pihole docker-compose.yml
    template:
      src: templates/docker-compose-pihole.yml
      dest: /home/pi/pihole/docker-compose.yml
    tags: pihole
  - name: Create motioneye directory
    file:
      path: /home/pi/motioneye
      state: directory
    tags: motioneye
  - name: Copy motioneye docker-compose.yml
    template:
      src: templates/docker-compose-motioneye.yml
      dest: /home/pi/motioneye/docker-compose.yml
    tags: motioneye
  - name: Create tinyfilemanager directory
    file:
      path: /home/pi/tinyfilemanager
      state: directory
    tags: tinyfilemanager
  - name: Copy tinyfilemanager docker-compose.yml
    template:
      src: templates/docker-compose-tinyfilemanager.yml
      dest: /home/pi/tinyfilemanager/docker-compose.yml
    tags: tinyfilemanager
