- name: Install python3-pip
  apt:
    name: python3-pip
    state: present

- name: Download ffmpeg package
  command: wget https://github.com/ccrisan/motioneye/wiki/precompiled/ffmpeg_3.1.1-1_armhf.deb

- name: Install ffmpeg package
  command: dpkg -i ffmpeg_3.1.1-1_armhf.deb

- name: Install dependencies
  apt:
    name: "{{ packages }}"
    state: present
    vars:
      packages:
        - python-dev
        - curl
        - libssl-dev
        - libcurl4-openssl-dev
        - libjpeg-dev
        - libx264-142
        - libavcodec56
        - libavformat56
        - libmysqlclient18
        - libswscale3
        - libpq5

- name: Download ffmpeg package
  command:  wget https://github.com/Motion-Project/motion/releases/download/release-4.0.1/pi_jessie_motion_4.0.1-1_armhf.deb

- name: Install ffmpeg package
  command: dpkg -i pi_jessie_motion_4.0.1-1_armhf.deb

- name: Install MotionEye
  pip:
    name: motioneye
    state: present
    executable: pip2

- name: Create MotionEye configuration directory
  file:
    path: /etc/motioneye
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Copy MotionEye configuration file
  command: cp /usr/local/share/motioneye/extra/motioneye.conf.sample /etc/motioneye/motioneye.conf
  args:
    creates: /etc/motioneye/motioneye.conf
