---
- name: Install dependencies
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - python3-pip
      - libssl-dev
      - libffi-dev
      - python-dev
      - python-setuptools
      - python-wheel
      - libjpeg-dev
      - libcairo2-dev
      - ffmpeg

- name: Install MotionEye
  pip:
    name: motioneye
    state: present

- name: Create MotionEye configuration directory
  file:
    path: /etc/motioneye
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Create MotionEye media directory
  file:
    path: /var/lib/motioneye
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Copy MotionEye configuration file
  template:
    src: motioneye.conf.j2
    dest: /etc/motioneye/motioneye.conf
    owner: root
    group: root
    mode: 0644
