- name: Add MotionEye repository
  apt_repository:
    repo: deb http://deb.motion-project.com/motion-project bullseye main
    state: present

- name: Add MotionEye repository key
  apt_key:
    url: http://deb.motion-project.com/motion-project.key
    state: present

- name: Update package list
  apt:
    update_cache: yes

- name: Install MotionEye
  apt:
    name: motioneye
    state: present

- name: Create MotionEye configuration directory
  file:
    path: /etc/motioneye
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Copy MotionEye configuration file
  template:
    src: templates/motioneye.conf.j2
    dest: /etc/motioneye/motioneye.conf
    owner: root
    group: root
    mode: 0644

- name: Enable MotionEye service
  systemd:
    name: motioneye
    state: started
    enabled: yes
