- name: Backup dhcpcd.conf
  copy:
    src: /etc/dhcpcd.conf
    dest: /etc/dhcpcd.conf.bak
    remote_src: yes

- name: Configure static IP address
  blockinfile:
    path: /etc/dhcpcd.conf
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    block: |
      interface eth0
      static ip_address=192.168.5.198/24
      static routers=192.168.5.1
      static domain_name_servers=8.8.8.8 8.8.4.4

- name: Restart dhcpcd service
  service:
    name: dhcpcd
    state: restarted