- name: Install and upgrade packages
  become: true
  shell: |
    sudo apt update && sudo apt upgrade -y

- name: Remove old Docker packages
  become: true
  shell: |
    sudo apt remove -y docker-ce*
    sudo apt-get autoremove -y

- name: Install Docker
  become: true
  shell: |
    curl -sSL https://get.docker.com | sh

- name: Add user to Docker group
  become: true
  shell: |
    sudo usermod -a -G docker $USER

- name: Install pip and Docker Compose
  become: true
  shell: |
    sudo apt install -y python3-pip python3
    sudo python3 -m pip install docker-compose
