- name: Install a list of packages
  apt:
    name: libffi-dev
    update_cache: yes
- name: Install a list of packages
  apt:
    name: libssl-dev
    update_cache: yes
- name: Install a list of packages
  apt:
    name: python3
    update_cache: yes
- name: Install a list of packages
  apt:
    name: python3-pip
    update_cache: yes

- name: Remove python-configparser package
  apt:
    name: python-configparser
    state: absent

- name: get docker convenience script
  shell: curl -fsSL https://get.docker.com -o get-docker.sh

- name: install docker
  shell: sh get-docker.sh
  args:
    creates: /usr/bin/docker

- name: make pi user execute docker commands
  shell: usermod -aG docker pi

- name: install docker-compose
  shell: pip3 -v install docker-compose
  args:
    creates: /usr/local/bin/docker-compose
