- name: Install Docker Compose
  apt:
    name: docker-compose
    state: present

- name: Copy docker-compose.yml file
  copy:
    src: templates/docker-compose.yml
    dest: /home/pi/home_assistant/docker-compose.yml

- name: Start Home Assistant container
  command: docker-compose up -d
  args:
    chdir: /home/pi/home_assistant
