- name: Install Docker Compose
  become: true
  shell: sudo curl -L "https://github.com/docker/compose/releases/download/1.28.6/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose


- name: Install Docker Compose 2
  become: true
  shell: sudo chmod +x /usr/local/bin/docker-compose

- name: Create pihole directory
  file:
    path: /home/pi/pihole
    state: directory

- name: Copy the docker-compose.yml file
  copy:
    src: templates/docker-compose.yml
    dest: /home/pi/pihole/docker-compose.yml

- name: Create pihole container
  command: docker-compose -f /home/pi/pihole/docker-compose.yml up -d
